### ISSUE TITLE
Hathor Built-in Merged Mining Stratum not working

### ISSUE THREAD

**Issue by goodthebest** [HathorNetwork/hathor-core#112]
I've installed hathor-core node and it's running and completely synced.  however when I am trying to start hathor's builtin merged mining it throws error

![image](https://user-images.githubusercontent.com/1715740/86254283-097c8000-bbcf-11ea-8b88-4706d4130f4f.png)

I'm using this pattern to activate stratum for merged mining
`hathor-cli run_merged_mining --port 9000 --hathor-api http://localhost:8080/ --hathor-address HATHOR_ADDRESS --bitcoin-rpc http://foo:bar@192.168.1.34:8332 --bitcoin-address BITCOIN_ADDRESS`

Using this guide
https://hathor.network/resources/merged-mining-guide/

**Comment by jansegre** [comment]
That error suggests that `hathor-cli` was somehow launched from another Python (with version less than 3.5, because typing annotation syntax was introduced in Python 3.6).

Although the guide could have been more explicit, it was probably omitted so it doesn't get too long and repeat instructions that are common to all guides. But we should definitely try to improve this.

Since you got as far as running and syncing a hathor-core, the solution to your particular case should be fairly simple, but it depends on how you're running the fullnode.

It should boil down to running the same command you used for the full node and replacing `run_node ...` for `run_merged_mining ...` (adapting arguments as needed).

If you continue having problems and want quicker responses, feel free to reach out for help on our [Discord](https://discord.gg/aWukZZX). I'm usually online there as well as the other devs.
