### ISSUE TITLE
Unhandled exception when decoding unknown transaction

### ISSUE THREAD

**Issue by obiyankenobi** [HathorNetwork/hathor-core#127]
![image](https://user-images.githubusercontent.com/3236756/88976882-c805f000-d2b4-11ea-8c0e-89c190f3e708.png)

Got this when trying to decode a tx that is not in the mainnet, using the explorer decode tool. I created it on my local testnet. I actually thought that I'd be able to decode it using the tool on the explorer, but it seems the full node gets info from the storage.

The used hex:
```
0001000100000003f168ad1f537576a94ca1e841a63de48e03c966bd8e8c7731b249b50fab02006a473045022100ab50341f66d59f0981e30be074df25aae15288bde6e139d916ecac50056b405e02205705a1b6dc39a039976246292126b4c998bda219548c6e2d8df66237c273a6c121037c64ba2ee99d4352e4f5902ff9ae895e1d0e1ab096e4514fea6086f16d0e6dae403085db5e33a91d5f233c0102000003e280e391ca31e58856509a54f9cd459b9f09ce3d5adf0fe1f31552b80500000cafb17528e2af824d413ab00a1088146f7abaab110f910c8e41359947940002ac1e
```

**Comment by pedroferreira1** [comment]
This is not a bug, in my opinion. We designed the decode exactly like this, it's the expected behaviour.

We wanted the decode tx page to be exactly like a transaction detail screen, so we need to access the storage to get metadata information.

We could create an issue as an enhancement to stop returning the metadata (which we should discuss because it was not the first idea) or create a 'decode' only for transaction data and a 'full decode' for everything. Either way I don't think it's a bug, given that we wanted it to be like this.

**Comment by obiyankenobi** [comment]
Yeah, I actually opened the issue so we handle the Unhandled Exception on the full node.

The other thing is another discussion and we should discuss in a separate place.

**Comment by jansegre** [comment]
I've made `hathor.util.api_catch_exceptions` decorator a while ago. If we just decorate the resource's handler method and add a `status_code = 404` (or `400`) on `TransactionDoesNotExist` it will work much more sanely.

**Comment by jansegre** [comment]
We have added many more protections to prevent this type of errors.
