### ISSUE TITLE
Spike: Dive deep into the coverage and check what improvements are required for the launch of the mainnet.

### ISSUE THREAD

**Issue by msbrogli** [HathorNetwork/hathor-core#23]

**Comment by obiyankenobi** [comment]
This is the coverage report for our current `dev` branch: [Coverage report.pdf](https://github.com/HathorNetwork/hathor-core/files/3762043/Coverage.report.pdf)

I had to remove stratum tests as they're still not working right. From the report, these are the files I feel need more investigation and could use more tests. Some of them have high coverage already (like hathor/crypto/util.py  96%), but are very important and should possibly reach 100%.

```
hathor/crypto/util.py  96%
hathor/manager.py  89%
hathor/p2p/downloader.py  77%
hathor/p2p/manager.py  78%
hathor/p2p/node_sync.py  86%
hathor/p2p/peer_discovery.py  41%
hathor/p2p/peer_id.py  85%
hathor/p2p/protocol.py  87%
hathor/p2p/states/base.py  89%
hathor/p2p/states/hello.py  81%
hathor/p2p/states/peer_id.py  80%
hathor/p2p/states/ready.py  93%
hathor/p2p/utils.py  79%
hathor/transaction/resources/push_tx.py  91%
hathor/transaction/resources/transaction.py  88%
hathor/transaction/scripts.py  95%
hathor/transaction/transaction_metadata.py  91%
hathor/wallet/resources/thin_wallet/send_tokens.py  74%
hathor/wallet/resources/thin_wallet/token_history.py  83%
```

**Comment by obiyankenobi** [comment]
Took a look at some of the files. My opinion:

hathor/crypto/util.py: just 3 lines missing coverage, seems it's better to reach 100% as it's related to the crypto part;

hathor/manager.py: will wait for stratum tests to also run, as some more lines might be covered by them. Overall, doesn't seem important parts are left out of tests;

hathor/p2p/downloader.py: tests missing mostly on the retry logic;

hathor/p2p/manager.py: there are no important areas that need cover. We can increase it for improving numbers, but I'd say it's a low priority;

hathor/p2p/node_sync.py: most important parts already covered. I'd only improve tests for `handle_get_data` and `handle_not_found`.

hathor/p2p/peer_discovery.py: doesn't seem very relevant, even though coverage is really low;

hathor/p2p/peer_id.py: we should add tests for entrypoint and certificate validation;

hathor/p2p/protocol.py: nothing relevant seems to missing from tests;

hathor/p2p/states/hello.py: need to improve testing on `handle_hello`;

hathor/p2p/states/peer_id.py: need to improve testing on `handle_peer_id`;

hathor/p2p/utils.py: just one extra function worth testing (`description_to_connection_string`);

hathor/transaction/resources/push_tx.py: have to test error cases;

hathor/transaction/scripts.py: very important part of the code. We should reach 100% coverage;

hathor/wallet/resources/thin_wallet/send_tokens.py: missing a lot of coverage due to stratum tests, need to analyze again later;

**Comment by pedroferreira1** [comment]
**hathor/crypto/util.py** and **hathor/transaction/scripts.py** for me more than just reach 100% we should validate that the tests are covering all the options and possibilities because are critic methods.

**hathor/p2p/peer_discovery.py** has the problem to depend on the DNS query (we could do a fake DNS server but have decided not to do it). Because of that some other tests depend on it, like `description_to_connection_string` and `handle_peer_id ` as you have mentioned.

**Comment by msbrogli** [comment]
> **hathor/crypto/util.py** and **hathor/transaction/scripts.py** for me more than just reach 100% we should validate that the tests are covering all the options and possibilities because are critic methods.
> 
> **hathor/p2p/peer_discovery.py** has the problem to depend on the DNS query (we could do a fake DNS server but have decided not to do it). Because of that some other tests depend on it, like `description_to_connection_string` and `handle_peer_id ` as you have mentioned.

We can separate into different methods and skip the coverage only in the direct call to the DNS client. All other pars can be tested separately. What do you think?

**Comment by msbrogli** [comment]
I agree with @obiyankenobi. I think we can create these task and add to the Backlog so we will prioritize them next planning.

I've checked that **base_transaction.py**, **block.py**, **token_creation.py**, **transaction.py**, and **scripts.py** are not 100%. Maybe we should do it for two reasons: (i) we are close to 100%; (ii) they are the most critical part.

**Comment by jansegre** [comment]
Looks good to me.
