### ISSUE TITLE
Some questions about merged mining

### ISSUE THREAD

**Issue by Grizzly1127** [HathorNetwork/hathor-core#248]
I'm a developer of the mining pool service.
Regarding the merged mining of hathor, I have a questions I want to ask, and I hope to get your answer.

When I write hathor's merged mining program in my service, do I need to construct htr_block_hash after getting the result through get_block_template?

I look forward to your reply.

**Comment by jansegre** [comment]
[The merged mining RFC](https://github.com/HathorNetwork/rfcs/blob/master/text/0006-merged-mining-with-bitcoin.md) covers all about constructing the bytes that are needed for making merged mining blocks. But it doesn't show how to use any API, that's is something we can definitely improve.

I'm not sure what you're calling `htr_block_hash`, maybe it is what the RFC calls `base_hash`, that is the hash that goes into the parent (for example BTC) chain's coinbase. If you're using `get_block_template` you will have to construct the `base_hash`.

I would also recommend using the merged mining websocket (`/v1a/mining_ws`) instead of `get_block_template`. You can try the API with `wscat -c https://miners.mainnet.hathor.network/v1a/mining_ws`, but I _highly_ recommend using your own node for production.

If you have any suggestions, like what type of examples would help, or if there is any information we can add to an API that would make your life easier. I'd love to hear it.

**Comment by jansegre** [comment]
If you don't mind. I'll convert this to a Discussion since there isn't any particular bug or new feature on `hathor-core`.
