### ISSUE TITLE
Sentry integration is not working for all exceptions

### ISSUE THREAD

**Issue by luislhl** [HathorNetwork/hathor-core#286]
We found an exception that is not being sent to Sentry even when it's enabled.

I ran some tests to confirm, and every exception I generated through the API was successfully sent, but this one which happened in the stratum server in the same full-node I tested was not being sent: https://github.com/HathorNetwork/hathor-core/issues/280

So, I suspect it has something to do with it having happened in the stratum, but I'm not really sure, we need to investigate this further to confirm and to find a fix.

**Comment by jansegre** [comment]
This is probably because it's an exception that happened during logging, and the system that catches exception requires the logging to work correctly. Any such exception should be considered a bug and not a "normal exception". I think we already catch these with some of the alerts that look for log patterns, so we might not have to do anything directly in this issue anymore.
