### ISSUE TITLE
`AddressIndex.get_sorted_from_address()` has different behaviors between memory and rocksdb implementation

### ISSUE THREAD

**Issue by msbrogli** [HathorNetwork/hathor-core#416]
The method docstring does not specify what the sorting key is. The memory implementation sorts by hash, while the rocksdb implementation sorts by timestamp.

**Comment by jansegre** [comment]
I see. Would there be any issue anywhere (maybe wallet-service or headless-wallet) if this behavior changed from a fullnode upgrade?

I see two options to make them have the same behavior:

1. change the memory implementation to sort by timestamp, which would cause a change in behavior from one version to another
2. change the rocksdb implementation to sort by hash, which will need a migration to be implemented to make sure that the database is not corrupted

I'm leaning towards the first option, just because sorting by timestamp makes much more sense to me.

**Comment by msbrogli** [comment]
I guess @pedroferreira1 can help us here. As far as I understood, we can safely sort by timestamp.

**Comment by pedroferreira1** [comment]
This method is only used in one API to get all tx ids of an address in a fixed order, so we can paginate this API using the last hash sent.

Given that, changing the sort field won't create any problem, only if a use case is using this API for another case (which I think is unlikely). I feel we can change this behavior and warn in the change log

**Comment by jansegre** [comment]
The memory implementation sorts by timestamp too now.
