### ISSUE TITLE
Remove tx when any unhandled exception raises when adding it to the DAG

### ISSUE THREAD

**Issue by msbrogli** [HathorNetwork/hathor-core#6]
The action of adding a new transaction to the DAG is comprised of several tasks, including updating its metadata and running the consensus algorithm.

Currently, the transaction is saved into the storage before doing other internal tasks. If anything goes wrong during these tasks, we must remove the transaction from the DAG.

MR: https://gitlab.com/HathorNetwork/hathor-python/merge_requests/319

**Comment by jansegre** [comment]
How does this interact with re-syncing?

Suppose these two cases:

1. Transactions A and B arrive, in which A is a parent of B. There is a storage exception (disk full, or temporary failure) when saving A, this means A must be removed and B will fail to be added because one of its parents, A, does not exist. The node should re-sync from a point that is has the chance to receive A and B again
2. Transactions A and B arrive, in which A is a parent of B, but A is malformed, such that it will always fail to be added, no matter what, B won't be added as well. But we should we try to re-sync?

Whatever policy we have for trying to re-sync, we have to manage the balance of recovering from expected failures (disk full or failures will happen) and DoS (depending on how we handle the 2nd case it would be trivial to DoS a node).

**Comment by msbrogli** [comment]
> How does this interact with re-syncing?
> 
> Suppose these two cases:
> 
> 1. Transactions A and B arrive, in which A is a parent of B. There is a storage exception (disk full, or temporary failure) when saving A, this means A must be removed and B will fail to be added because one of its parents, A, does not exist. The node should re-sync from a point that is has the chance to receive A and B again
> 2. Transactions A and B arrive, in which A is a parent of B, but A is malformed, such that it will always fail to be added, no matter what, B won't be added as well. But we should we try to re-sync?
> 
> Whatever policy we have for trying to re-sync, we have to manage the balance of recovering from expected failures (disk full or failures will happen) and DoS (depending on how we handle the 2nd case it would be trivial to DoS a node).

We don't have to worry about the reason a transaction has failed to be added. If A is malformed, no other full node will accept it, then no one will have B as well. But, if A is valid and it failed because of a temporary failure, other full nodes will have it and it will be synced eventually.

**Comment by obiyankenobi** [comment]
The most important thing is that the indexes have to be updated accordingly. We can't end up with a tx on the index which is not on disk, otherwise it will never be sent. Also, tips index and transactions index can't diverge.
